name: Running all tests

on:
  pull_request:
    branches: [ main ]
    paths:
      - D:/Projects/**
      - .github/workflows/run-tests.yml
  workflow_dispatch:

jobs:
  Testing:
    runs-on: ubuntu-latest
    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          SA_PASSWORD: 'MyS3cureP@ss!'
          ACCEPT_EULA: "Y"
        options: >-
          --health-cmd "exit 0"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 1433:1433
  
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
          
      - name: Wait for SQL Server
        run: |
          apt-get update
          apt-get install -y mssql-tools
          echo "PATH=$PATH:/opt/mssql-tools/bin" >> ~/.bashrc
          source ~/.bashrc
          for i in {1..50}; do
            if /opt/mssql-tools/bin/sqlcmd -S sqlserver -U SA -P 'MyS3cureP@ss!' -Q "SELECT 1" &> /dev/null; then
              echo "SQL Server is ready."
              break
            fi
            echo "Waiting for SQL Server..."
            sleep 5
          done

      - name: Restore dependencies
        run: dotnet restore MarketApi/MarketApi.sln

      - name: Run unit tests
        run: dotnet test 'Market.NUnit/Market.NUnit.csproj' --logger "console;verbosity=detailed" --blame

      - name: Run integration tests
        env:
          ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=MarketDB;User Id=SA;Password=MyS3cureP@ss!;TrustServerCertificate=True"
        run: dotnet test 'Market.xUnit.Integration/Market.xUnit.Integration.csproj' --logger "console;verbosity=detailed" --blame